Atid='https://atid.store/'
Accsosery="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[5]/a[1]"
select="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[2]/div[2]/a[1]"
button="//button[contains(text(),'Add to cart')]"
cartSelect="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
CartAdd="//h1[contains(text(),'Cart')]"
AmoutSelect="//input[@id='coupon_code']"
S_loketer="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[2]/a[1]"
S_mane="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]/div[1]/a[1]"
S_button="//button[contains(text(),'Add to cart')]"
S_selector="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/a[1]"
S_Addcart="//a[contains(text(),'Anchor Bracelet')]"
S_chek="//input[@id='coupon_code']"
Women="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[4]/a[1]"
W_select="//h2[contains(text(),'Anchor Bracelet')]"
W_cart="//button[contains(text(),'Add to cart')]"
W_addcart="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/a[1]/div[1]/span[1]"
W_button="//a[contains(text(),'Anchor Bracelet')]"
W_chek="//input[@id='coupon_code']"

Mane="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[3]/a[1]"
M_select="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[3]/div[1]/a[1]/img[1]"
M_addCart="//button[contains(text(),'Add to cart')]"
M_check="//a[contains(text(),'ATID Green Tshirt')]"
M_input="//input[@id='coupon_code']"
home="//header/div[@id='ast-desktop-header']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[1]/a[1]"
shopKnow="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/a[1]/span[1]/span[1]"
ssearch="/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/input[1]"
corsor="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/*[1]"
h_check="//body/div[@id='page']/div[@id='content']/div[1]/div[2]/main[1]/div[1]/ul[1]/li[1]/div[1]/a[1]/img[1]"
filiter="//button[contains(text(),'Filter')]"
h_add="//h2[contains(text(),'ATID Black Shoes')]"
h_addtocart="//button[contains(text(),'Add to cart')]"
h_viewcart="//body/div[@id='page']/div[@id='content']/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/a[1]"
cupon="/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/button[1]"